server:
  port: 8080

spring:
  application:
    name: user-app
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.9.230:5432/lonbon_agent_dev?useUnicode=true&characterEncoding=utf8&ssl=false&timezone=Asia/Dubai
    username: lonbon
    password: Lonbon#DB2024_
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000
      keepalive-time: 60000
      max-lifetime: 1800000
      validation-timeout: 5000

logging:
  level:
    root: INFO
    com.easy.query.core: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
  show-actuator: true

# 配置数据源对应的 easy-query 信息
easy-query:
  database: pgsql
  name-conversion: underlined
  print-sql: true
